# Mengukur Jarak Antar Data Campuran

Mengukur jarak antar data adalah proses menghitung tingkat perbedaan (dissimilarity) atau kemiripan (similarity) antara dua objek dalam suatu dataset.
* Jika jarak = 0 maka kedua objek sama.
* Semakin kecil jarak maka semakin mirip.
* Semakin besar jarak maka semakin berbeda.

Metode yang digunakan tergantung pada tipe datanya:
* Nominal & Binary Simetris = Simple Matching
* Binary Asimetris = Jaccard
* Numerik = Euclidean atau Manhattan (Minkowski)
* Ordinal = Ranking lalu dihitung seperti numerik
* Data Campuran = Gower Distance

Pengukuran jarak ini penting dalam proses seperti clustering, KNN, dan analisis data lainnya.

## 1. Mengukur Jarak Antar Data Campuran dengan menggunakan code (Python)

### 1. Import Library
Kode di bawah ini berfungsi untuk Memanggil library yang dipakai untuk mengambil data dari PostgreSQL, mengolah data.

In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

**Penjelasan**:
* pandas (pd) dipakai untuk manipulasi data tabel (DataFrame).
* numpy (np) dipakai untuk operasi numerik dan seleksi kolom numerik.
* create_engine dipakai untuk membuat koneksi ke PostgreSQL melalui SQLAlchemy.

### 2. Mengakses dan menampilkan Dataset Iris dari database PostgreSQL

Mengambil dataset langsung dari database PostgreSQL agar sumber datanya jelas dan sesuai instruksi.

In [2]:
engine = create_engine(
    "postgresql+psycopg2://postgres:ansdka6272@localhost:5432/Pendata"
)

query = 'SELECT * FROM public."bank";'
df = pd.read_sql('SELECT * FROM public."bank" ORDER BY id;', engine)

df.head(100)

,age,job,marital,education,default_,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit,id
0,51,entrepreneur,married,2,no,-799,no,yes,cellular,15,jul,1001,3,-1,0,unknown,yes,1
1,46,admin.,married,2,no,-522,yes,no,cellular,27,mar,243,3,239,13,other,yes,2
2,42,admin.,single,2,no,684,no,no,cellular,4,jun,207,1,-1,0,unknown,yes,3
3,27,student,single,2,no,6036,no,no,cellular,31,mar,175,1,181,1,failure,yes,4
4,31,admin.,single,2,no,410,no,no,cellular,23,apr,342,1,-1,0,unknown,yes,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,39,management,married,3,no,-190,no,yes,unknown,11,jun,893,8,-1,0,unknown,yes,96
96,57,housemaid,married,1,no,625,no,yes,unknown,11,jun,867,1,-1,0,unknown,yes,97
97,52,retired,married,0,no,293,no,no,unknown,11,jun,706,1,-1,0,unknown,yes,98
98,59,retired,married,0,no,1033,no,no,unknown,11,jun,1199,1,-1,0,unknown,yes,99
99,56,blue-collar,married,2,no,1210,no,no,unknown,11,jun,935,1,-1,0,unknown,yes,100

**Penjelasan :**
* create_engine(...) membuat objek koneksi database.
* Format koneksi: postgresql+psycopg2://user:password@host:port/nama_database.
* query berisi perintah SQL untuk mengambil semua data dari tabel bank.
* pd.read_sql() mengeksekusi query dan hasilnya masuk ke DataFrame df.
* df.head() menampilkan 5 baris pertama untuk memastikan data terbaca.

### 3. Menampilkan Informasi Database
Menunjukkan bahwa data benar-benar berasal dari database PostgreSQL

In [3]:
print("Host:", "127.0.0.1")
print("Port:", 5432)
print("Database:", "Pendata")
print("Table:", 'public."bank"')
print("Query:", query)

Host: 127.0.0.1
Port: 5432
Database: Pendata
Table: public."bank"
Query: SELECT * FROM public."bank";

**Penjelasan :**
* print() dipakai untuk menuliskan informasi koneksi sebagai dokumentasi laporan.
* Variabel query dicetak agar pembaca tahu data diambil dengan SQL.

### 4. Dimensi Dataset
Mengetahui ukuran dataset untuk memahami skala analisis yang akan dilakukan.

In [4]:
print("Jumlah baris:", df.shape[0])
print("Jumlah kolom:", df.shape[1])

Jumlah baris: 10969
Jumlah kolom: 18

**Penjelasan :**
* df.shape menghasilkan tuple (jumlah_baris, jumlah_kolom).
* shape[0] untuk jumlah data.
* shape[1] untuk jumlah fitur.

### 5. Struktur dan Tipe Data
Mengidentifikasi tipe data setiap kolom serta memastikan tidak terdapat nilai kosong yang tidak terdeteksi.

In [5]:
print("Tipe Data setiap kolom:")
df.info()

Tipe Data setiap kolom:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10969 entries, 0 to 10968
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        10969 non-null  int64
 1   job        10969 non-null  object
 2   marital    10969 non-null  object
 3   education  10969 non-null  object
 4   default_   10969 non-null  object
 5   balance    10969 non-null  int64
 6   housing    10969 non-null  object
 7   loan       10969 non-null  object
 8   contact    10969 non-null  object
 9   day        10969 non-null  int64
 10  month      10969 non-null  object
 11  duration   10969 non-null  int64
 12  campaign   10969 non-null  int64
 13  pdays      10969 non-null  int64
 14  previous   10969 non-null  int64
 15  poutcome   10969 non-null  object
 16  deposit    10969 non-null  object
 17  id         10969 non-null  int64
dtypes: int64(8), object(10)
memory usage: 1.5+ MB

**Penjelasan :**
* df.info() menampilkan nama kolom, tipe data, serta jumlah nilai yang tidak kosong.

### 5. Menghitung jarak antar data

In [3]:
import numpy as np
import pandas as pd

# ambil 10 data pertama
df_copy = df.head(10).copy()

# kelompok fitur
kolom_numerik = ['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']
kolom_nominal = ['job', 'marital', 'contact', 'month', 'poutcome']
kolom_binary = ['default_', 'housing', 'loan', 'deposit']
kolom_ordinal = ['education']

# ordinal => numerik
ranking_education = {'primary': 1, 'secondary': 2, 'tertiary': 3}
df_copy['education'] = df_copy['education'].astype(str).str.lower().map(ranking_education)
df_copy['education'] = (df_copy['education'] - 1) / (3 - 1)

# ordinal masuk ke numerik
kolom_numerik_final = kolom_numerik + kolom_ordinal

# hitung range
range_kolom = {}
for kolom in kolom_numerik_final:
    range_kolom[kolom] = df_copy[kolom].max() - df_copy[kolom].min()

# jumlah data
n = len(df_copy)

# matrix jarak
matrix_jarak = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        jumlah_jarak = 0
        jumlah_delta = 0

        data_i = df_copy.iloc[i]
        data_j = df_copy.iloc[j]

        # nominal
        for kolom in kolom_nominal:
            if pd.notna(data_i[kolom]) and pd.notna(data_j[kolom]):
                jarak = 0 if data_i[kolom] == data_j[kolom] else 1
                jumlah_jarak += jarak
                jumlah_delta += 1

        # binary asimetris
        for kolom in kolom_binary:
            nilai_i = 1 if str(data_i[kolom]).lower() == 'yes' else 0
            nilai_j = 1 if str(data_j[kolom]).lower() == 'yes' else 0

            if not (nilai_i == 0 and nilai_j == 0):
                jarak = 0 if nilai_i == nilai_j else 1
                jumlah_jarak += jarak
                jumlah_delta += 1

        # numerik + ordinal
        for kolom in kolom_numerik_final:
            if pd.notna(data_i[kolom]) and pd.notna(data_j[kolom]):
                rentang = range_kolom[kolom]

                if rentang != 0:
                    jarak = abs(data_i[kolom] - data_j[kolom]) / rentang
                    jumlah_jarak += jarak
                    jumlah_delta += 1

        if jumlah_delta != 0:
            matrix_jarak[i, j] = jumlah_jarak / jumlah_delta

# tampilkan matrix
labels = [f"Data_{i+1}" for i in range(n)]
jarak_df = pd.DataFrame(matrix_jarak, index=labels, columns=labels).round(3)

print("Matrix Jarak Campuran: ")
display(jarak_df)

Matrix Jarak Campuran:

,Data_1,Data_2,Data_3,Data_4,Data_5,Data_6,Data_7,Data_8,Data_9,Data_10
Data_1,0.000,0.566,0.487,0.728,0.493,0.451,0.447,0.419,0.338,0.423
Data_2,0.566,0.000,0.586,0.573,0.566,0.535,0.683,0.544,0.581,0.666
Data_3,0.487,0.586,0.000,0.476,0.176,0.113,0.318,0.311,0.259,0.192
Data_4,0.728,0.573,0.476,0.000,0.406,0.452,0.401,0.486,0.646,0.445
Data_5,0.493,0.566,0.176,0.406,0.000,0.151,0.225,0.272,0.329,0.185
Data_6,0.451,0.535,0.113,0.452,0.151,0.000,0.258,0.291,0.286,0.240
Data_7,0.447,0.683,0.318,0.401,0.225,0.258,0.000,0.315,0.421,0.164
Data_8,0.419,0.544,0.311,0.486,0.272,0.291,0.315,0.000,0.314,0.362
Data_9,0.338,0.581,0.259,0.646,0.329,0.286,0.421,0.314,0.000,0.278
Data_10,0.423,0.666,0.192,0.445,0.185,0.240,0.164,0.362,0.278,0.000

**Penjelasan :**

* df_copy = df.head(10).copy() mengambil 10 data pertama dari DataFrame df agar perhitungan jarak lebih cepat dan menghasilkan matrix jarak 10 × 10.
* kolom_numerik, kolom_nominal, kolom_binary, dan kolom_ordinal digunakan untuk mengelompokkan atribut berdasarkan tipe datanya sehingga setiap atribut dapat dihitung dengan metode jarak yang sesuai.
* ranking_education = {'primary': 1, 'secondary': 2, 'tertiary': 3} digunakan untuk mengubah atribut ordinal education menjadi peringkat numerik.
* df_copy['education'] = df_copy['education'].astype(str).str.lower().map(ranking_education) mengubah nilai kategori education menjadi angka:
a. primary = 1
b. secondary = 2
c. tertiary = 3
* df_copy['education'] = (df_copy['education'] - 1) / (3 - 1) melakukan normalisasi atribut ordinal ke skala 0–1 menggunakan rumus: **(r−1)/(M−1)**
* kolom_numerik_final = kolom_numerik + kolom_ordinal menggabungkan atribut numerik asli dengan atribut ordinal yang sudah diubah menjadi numerik sehingga education ikut dihitung sebagai atribut numerik.
* range_kolom = {} digunakan untuk menyimpan rentang nilai setiap atribut numerik, yaitu selisih antara nilai maksimum dan minimum.
* range_kolom[kolom] = df_copy[kolom].max() - df_copy[kolom].min() menghitung rentang (max − min) setiap atribut numerik yang akan digunakan untuk normalisasi jarak.
* n = len(df_copy) menyimpan jumlah data yang digunakan dalam perhitungan.
* matrix_jarak = np.zeros((n, n)) membuat matrix kosong berukuran n × n untuk menyimpan hasil jarak antar setiap pasangan data.
* for i in range(n) dan for j in range(n) digunakan untuk membandingkan setiap data dengan semua data lainnya, sehingga semua pasangan data dapat dihitung jaraknya.
* data_i = df_copy.iloc[i] mengambil data pada baris ke-i sebagai objek pertama.
* data_j = df_copy.iloc[j] mengambil data pada baris ke-j sebagai objek kedua.
* Pada bagian Nominal, jarak dihitung dengan metode simple matching:
  
    a. jika nilai atribut sama maka jarak = 0

    b. jika nilai atribut berbeda maka jarak = 1

* Pada bagian Binary Asimetris, nilai atribut diubah menjadi:
  
    a. yes = 1

    b. selain yes = 0

    Kemudian:

    a. jika pasangan bernilai 00 → atribut tidak dihitung

    b. jika tidak 00 → dihitung menggunakan konsep Jaccard

* Pada bagian Numerik + Ordinal, jarak dihitung menggunakan rumus normalisasi: **∣x−y∣/(max−min)**
agar semua atribut berada pada skala 0–1 sebelum dijumlahkan.
* jumlah_jarak += jarak digunakan untuk menambahkan kontribusi jarak dari setiap atribut.
* jumlah_delta += 1 digunakan untuk menghitung jumlah atribut yang benar-benar digunakan dalam perhitungan.
* matrix_jarak[i, j] = jumlah_jarak / jumlah_delta menghitung nilai jarak campuran akhir antara dua data dengan membagi total kontribusi jarak dengan jumlah atribut yang dihitung.
* labels = [f"Data_{i+1}" for i in range(n)] membuat label baris dan kolom pada matrix agar lebih mudah dibaca.
* jarak_df = pd.DataFrame(matrix_jarak, index=labels, columns=labels).round(3) mengubah matrix menjadi DataFrame dan membatasi angka menjadi 3 digit di belakang koma.
* display(jarak_df) menampilkan matrix jarak campuran dalam bentuk tabel sehingga mudah dianalisis.